on:
  push:
    tags:
      # This is slightly annoying. Is there a better way to do this?
      - 'llvm-bitcursor-v*'
      - 'llvm-bitstream-v*'
      - 'llvm-constants-v*'

name: release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: ${{ contains(github.ref, 'pre') || contains(github.ref, 'rc') }}

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: publish release
        run: |
          echo ${{ secrets.CRATES_IO_TOKEN }} | cargo login
          tag="${GITHUB_REF#refs/tags/}"
          package_being_published="${tag%-v*}"
          cd "${package_being_published}" && cargo publish
